#!/bin/bash
# For more info, see:
# https://unix.stackexchange.com/a/346572/236646
cvlc \
    --no-video-deco \
    --no-embedded-video \
    --screen-fps=20 \
    --screen-top=0 \
    --screen-left=1920 \
    --screen-width=1920 \
    --screen-height=1080 \
    screen://
