#!/usr/bin/python
import argparse;

"""
Parse the arguments
"""
parser = argparse.ArgumentParser(
    description = 'Maintains symbolic links to a repo of config files in ~/.etch'
)
parser.add_argument('paths', metavar='path', type=str, nargs='+', 
                    help='a file or directory')
parser.add_argument('--role', '-r', action='store', default='default',
                    help='optional role that will override \'default\'')
args = parser.parse_args()
print(args.role)
print(args.paths)

"""
Validate the paths. Each path:
1. Exists
2. Is not a symbolic link, or is not a directory in which there exists 
   a symbolic link, to something that is not a role path in ~/.home-utils
3. 
"""

"""
For each path:
Move to etch role path
Symbolic link 
"""
