#!/bin/bash
# VOLGROP='9700-vg'                # name of the volume group
# SNAPVOL='arch-root-snap'         # name of the snapshot to create
# FSAOPTS='-Z8 -j8'                # options to pass to fsarchiver (-j = number of cores)
# BACKDIR='/mnt/local-backup/'     # where to put the backup
# BACKNAM='9700-vg-arch-root'      # name of the archive

PATH="${PATH}:/usr/sbin:/sbin:/usr/bin:/bin"
TIMESTAMP="$(date +%Y%m%d-%Hh%M)"

if fsarchiver savefs ${FSAOPTS} ${BACKDIR}/${BACKNAM}-${TIMESTAMP}.fsa /dev/${VOLGROP}/${SNAPVOL}
then
    # md5sum ${BACKDIR}/${BACKNAM}-${TIMESTAMP}.fsa > ${BACKDIR}/${BACKNAM}-${TIMESTAMP}.md5
    RES=0
else
    echo "fsarchiver failed"
    RES=1
fi

exit ${RES}
