#!/bin/bash

BG_PATH=/home/brandon/Pictures/Backgrounds/2560x1600
BG_EXT=.jpg

NUM_FILES=$(ls $BG_PATH/*$BG_EXT | wc -l)
RANDOM_FILE=$(ls $BG_PATH/*$BG_EXT | sed -n "$((($RANDOM % $NUM_FILES) + 1))p")

# swaymsg "output * resolution 2560x1600 bg $RANDOM_FILE fill"

# The approach in the above comment needs to do some escaping to correct
# for odd characters but the symlink approach below works well as an
# alternative.

if [ -e $BG_PATH$BG_EXT ]; then
    rm $BG_PATH$BG_EXT
fi
ln -s $RANDOM_FILE $BG_PATH$BG_EXT
swaymsg "output * resolution 2560x1600 bg $BG_PATH$BG_EXT fill"
